templates:
  - template: subreddit
    columns:
      - {key: ts, label: Time}
      - {key: title, label: Title}
      - {key: score, label: Score}
      - {key: url, label: Link}
    sort: {key: ts, dir: desc}
    max_rows: 150
  - template: rss
    columns:
      - { key: ts,     label: Time }
      - { key: title,  label: Title }
      - { key: source, label: Source }
      - { key: url,    label: Link }
    sort: { key: ts, dir: desc }
    max_rows: 400
  - template: legistar_meetings
    columns:
      - {key: ts,              label: Date/Time }
      - {key: body_name,       label: Body }
      - {key: title,           label: Meeting }
      - {key: location,        label: Location }
      - {key: meeting_time,    label: Time }
      - {key: url,             label: Meeting Details }
      - {key: agenda_url,      label: Agenda }
    sort: { key: ts, dir: desc }
    max_rows: 200
  - template: ma_legislature_bills
    columns:
      - {key: ts,              label: Time }
      - {key: bill_number,     label: Bill Number }
      - {key: bill_title,      label: Title }
      - {key: table_type,      label: Type }
      - {key: source,          label: Source }
      - {key: url,             label: Bill Details }
    sort: { key: ts, dir: desc }
    max_rows: 150

sources:
  # Subreddits
  - module: subreddit
    template: subreddit
    stream: "Boston"
    tags: ["boston", "gossip"]
    interval_seconds: 900
    config:
      subreddit: "boston"
      listing: "new"
      limit: 10
  - module: subreddit
    template: subreddit
    stream: "Massachusetts Politics"
    tags: ["politics", "gossip"]
    interval_seconds: 900
    config:
      subreddit: "MassachusettsPolitics"
      listing: "new"
      limit: 10
  - module: subreddit
    template: subreddit
    stream: "Massachusetts"
    tags: ["gossip"]
    interval_seconds: 900
    config:
      subreddit: "massachusetts"
      listing: "new"
      limit: 10
  - module: subreddit
    template: subreddit
    stream: "MBTA"
    tags: ["mbta", "gossip"]
    interval_seconds: 900
    config:
      subreddit: "mbta"
      listing: "new"
      limit: 10
  - module: subreddit
    template: subreddit
    stream: "Cambridge"
    tags: ["cambridge", "gossip"]
    interval_seconds: 900
    config:
      subreddit: "CambridgeMA"
      listing: "new"
      limit: 10
  - module: subreddit
    template: subreddit
    stream: "Somerville"
    tags: ["somerville", "gossip"]
    interval_seconds: 900
    config:
      subreddit: "Somerville"
      listing: "new"
      limit: 10
  - module: subreddit
    template: subreddit
    stream: "Worcester"
    tags: ["worcester", "gossip"]
    interval_seconds: 900
    config:
      subreddit: "WorcesterMA"
      listing: "new"
      limit: 10
  - module: subreddit
    template: subreddit
    stream: "Newton"
    tags: ["newton", "gossip"]
    interval_seconds: 900
    config:
      subreddit: "newtonma"
      listing: "new"
      limit: 10

  # RSS Feeds
  - module: rss
    template: rss
    stream: "Boston.com"
    tags: ["boston", "news", "politics"]
    interval_seconds: 900
    config:
      url: "https://www.boston.com/feed/"
      limit: 20
  - module: rss
    template: rss
    stream: "Massachusetts Playbook"
    tags: ["news", "politics", "beacon hill", "laws"]
    interval_seconds: 900
    config:
      url: "https://rss.politico.com/massachusetts-playbook.xml"
      limit: 20
  - module: rss
    template: rss
    stream: "Boston Herald"
    tags: ["news", "politics", "beacon hill", "laws", "conservative"]
    interval_seconds: 900
    config:
      url: "https://www.bostonherald.com/news/politics/feed/"
      limit: 20
  - module: rss
    template: rss
    stream: "Howie Carr Show"
    tags: ["news", "gossip", "conservative"]
    interval_seconds: 900
    config:
      url: "https://howiecarrshow.com/feed/"
      limit: 20
  - module: rss
    template: rss
    stream: "Universal Hub"
    tags: ["news", "politics", "gossip", "mbta", "beacon hill", "blog"]
    interval_seconds: 900
    config:
      url: "https://uhub-direct.ghost.io/rss/"
      limit: 20
  - module: rss
    template: rss
    stream: "MassGOP"
    tags: ["politics", "conservative"]
    interval_seconds: 900
    config:
      url: "https://massgop.com/feed"
      limit: 10
  - module: rss
    template: rss
    stream: "Western Mass Politics & Insight"
    tags: ["news", "politics", "mbta", "beacon hill", "blog", "western mass"]
    interval_seconds: 900
    config:
      url: "https://wmasspi.com/feed"
      limit: 10
  - module: rss
    template: rss
    stream: "Progressive Democrats of Massachusetts"
    tags: ["politics", "beacon hill", "blog", "progressive"]
    interval_seconds: 900
    config:
      url: "https://progressivedemsofmass.wordpress.com/blog/feed/"
      limit: 10

  # Legistar
  - module: legistar_meetings
    template: legistar_meetings
    stream: boston-legistar-meetings
    tags: ["news", "politics", "mbta", "beacon hill", "official", "boston"]
    interval_seconds: 3600
    config:
      url: "https://boston.legistar.com"
      meeting_list_url: "Calendar.aspx"
      limit: 100
      mode: "replace"

  # Massachusetts Legislature Bills
  - module: ma_legislature_bills
    template: ma_legislature_bills
    stream: "Massachusetts Legislature Bills"
    tags: ["news", "politics", "beacon hill", "laws", "official", "legislation"]
    interval_seconds: 3600
    config:
      url: "https://malegislature.gov/Bills/RecentBills"
      limit: 40
      mode: "replace"
